import Head from "next/head";
import Link from "next/link";
import Layout from "components/layout";
import styles from "styles/home.module.sass";
import classNames from "classnames/bind";
import Airtable from "airtable";
import * as auth from "next-auth/client";

const cx = classNames.bind(styles);
const airtable = new Airtable({ apiKey: "keyYlwgYr8v5ereBr" });

// console.log("AIRTABLE_API_KEY", process.env.AIRTABLE_API_KEY);
// const airtable = new Airtable();

const base = airtable.base("appWyj8JIUwc8RcsW");
const table = base("main").select();

table.eachPage(async (records, next) => {
  records.forEach((record) => {
    console.log("Retrieved", record.get("Name"));
    console.log(record);
    // record.fields.forEach(console.log)
  });
  next();
}, console.log);

export default function Home() {
  // const [session, loading] = auth.useSession();
  // console.log(session || `loading ${loading}`);
  // if (!session) auth.signIn();
  // if (session) console.log(session);

  return (
    <Layout>
      <Head>
        <title>My Next Web App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1 onClick={() => auth.signIn()}>My Next Web App</h1>

      <div className={cx("grid")}>
        <Link href="/profile">
          <a className={styles.card}>
            <h2>Profile -&gt;</h2>
            <p>Upload files to firebase storage.</p>
          </a>
        </Link>

        {/* <Link href="/chat">
          <a className={styles.card}>
            <h2>Chat -&gt;</h2>
            <p>Live group chat useing firebase firestore!</p>
          </a>
        </Link> */}

        <Link href="/components">
          <a className={styles.card}>
            <h2>Components -&gt;</h2>
            <p>Discover my components.</p>
          </a>
        </Link>

        <Link href="/about">
          <a className={styles.card}>
            <h2>About -&gt;</h2>
            <p>Find out more about me.</p>
          </a>
        </Link>
      </div>
    </Layout>
  );
}
